name: Push Workflow
on:
    push:
        branches:
            - dev
    workflow_dispatch:
jobs:
    test_schedule:
        env:
            DEMO_ENV: ${{ secrets.MY_SECRET }}
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "$DEMO_ENV"
            - name: Step 2
              env:
                  DEMO_VAR: ${{ vars.REPOVAR }}
              run: echo Var $DEMO_VAR
